#!/bin/sh

if ! [ -f bin/unit_tests ]; then
    echo "Are you sure you ran make ?" 1>&2
    exit 66
fi

echo "Running unit tests."
bin/unit_tests

echo -e "\nRunning pretty printer tests."
bin/print_tests

exit $?
